# Generated by Django 3.2.5 on 2021-08-08 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=255, unique=True)),
                ('nombres', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('cedula', models.CharField(max_length=255, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('tipo_usuario', models.IntegerField(choices=[(1, 'Supervisor'), (2, 'Fiscalizador'), (3, 'Administrador')], default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nemonico_actividad', models.CharField(max_length=255)),
                ('texto_descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_actividades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linserman.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=255)),
                ('sector', models.CharField(max_length=255)),
                ('punto_cardinal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadasContratos',
            fields=[
                ('id_coordenada', models.AutoField(primary_key=True, serialize=False)),
                ('coordenadas_googleMaps', models.CharField(max_length=255)),
                ('ubicacion_googleMaps', models.CharField(max_length=255)),
                ('id_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linserman.contrato')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linserman.sector'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
