# Generated by Django 3.2.5 on 2021-08-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linserman', '0002_auto_20210809_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='id_sector',
            new_name='sectores',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='id_usuario',
            new_name='usuarios',
        ),
        migrations.RenameField(
            model_name='contratoxsector',
            old_name='id_actividad',
            new_name='actividades',
        ),
        migrations.RenameField(
            model_name='contratoxsector',
            old_name='id_sector',
            new_name='sector_data',
        ),
        migrations.RenameField(
            model_name='sectorxactividad',
            old_name='id_actividad',
            new_name='actividad_data',
        ),
    ]
