# Generated by Django 3.2.5 on 2021-08-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linserman', '0004_auto_20210811_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='nombre_contrato',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
