# Generated by Django 3.2.5 on 2021-08-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linserman', '0007_auto_20210822_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoxsector',
            name='actividades',
            field=models.ManyToManyField(to='linserman.Actividad'),
        ),
    ]
