# Generated by Django 3.2.5 on 2021-08-23 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linserman', '0010_alter_contratoxsector_actividades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SectorXActividad',
        ),
    ]
