# Generated by Django 3.2.5 on 2021-08-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linserman', '0011_delete_sectorxactividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
