# Generated by Django 3.2.5 on 2021-09-13 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linserman', '0014_auto_20210913_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa',
        ),
    ]
